- name: create ansible user
  user:
    name: ansible
    system: yes
    
- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
    
- name: Set authorized keys taken from url
  authorized_key:
    user: ansible
    state: present
    key: https://github.com/condolas.keys
